DROP TABLE users;

CREATE TABLE users (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    passwordHash VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    points FLOAT
  );